"""plan price_stars

Revision ID: 0a3999d37c4b
Revises: ad4c7bae5ca9
Create Date: 2026-07-06 17:48:07.997134

"""
from alembic import op
import sqlalchemy as sa


revision = '0a3999d37c4b'
down_revision = 'ad4c7bae5ca9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('price_stars', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'price_stars')
    # ### end Alembic commands ###
