"""server multi-transport fields

Revision ID: 35681ec69265
Revises: 0a3999d37c4b
Create Date: 2026-07-06 18:35:40.102157

"""
from alembic import op
import sqlalchemy as sa


revision = '35681ec69265'
down_revision = '0a3999d37c4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_servers', sa.Column('transport', sa.String(length=16), nullable=False))
    op.add_column('vpn_servers', sa.Column('security', sa.String(length=16), nullable=False))
    op.add_column('vpn_servers', sa.Column('network_path', sa.String(length=255), nullable=False))
    op.add_column('vpn_servers', sa.Column('header_host', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vpn_servers', 'header_host')
    op.drop_column('vpn_servers', 'network_path')
    op.drop_column('vpn_servers', 'security')
    op.drop_column('vpn_servers', 'transport')
    # ### end Alembic commands ###
