"""subscription reminder_sent_at

Revision ID: ad4c7bae5ca9
Revises: 08b70bc87253
Create Date: 2026-07-06 09:30:55.879192

"""
from alembic import op
import sqlalchemy as sa


revision = 'ad4c7bae5ca9'
down_revision = '08b70bc87253'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'reminder_sent_at')
    # ### end Alembic commands ###
